[project]
name = "audio-merger"
version = "0.1.0"
description = "A tool for merging multiple audio files using pydub"
requires-python = ">=3.8"

[tool.poetry.dependencies]
python = ">=3.8"
pydub = ">=0.25.1"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"